# See also: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html

sudo: false
language: python
python:
  - "3.6"

install:
  # ----- Setup Miniconda -----
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a  # Useful for debugging any issues with conda
  - conda env create -f environment.yml
  - source activate pytornado

  # ----- Install PyPI requirements and PyTornado itself -----
  - pip install numpy
  - python setup.py install
  - pip install -r requirements.txt

script:
  - pytest -v --cov=pytornado --cov-report=html tests/

after_success:
  - codecov
