# CONDA requirements file
# * Only packages which are not available on PyPI

name: pytornado
channels:
  - conda-forge
  - dlr-sc  # See: https://anaconda.org/DLR-SC/repo
dependencies:
  - pip
  # Tigl and Tixi
  - tigl3>=3.0.0rc
  - tixi3>=3.0.3
